name: demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-94.0.dev <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  assets:
     - assets/image/
     - assets/fonts/
   


  uses-material-design: true
fonts:
    - family: Poppins 
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300